# Configuración de ejemplo para el Generador de Thumbnails
# Copia este archivo como config.yaml y personaliza según tus necesidades

# Dimensiones del canvas final
canvas:
  width: 1920      # Ancho en píxeles
  height: 1080     # Alto en píxeles

# Configuración del fondo
background:
  blur_radius: 15  # Radio del desenfoque gaussiano

# Configuración del texto
text:
  max_width: 0.8          # Porcentaje del ancho del canvas (0.0-1.0)
  line_spacing: 1.1       # Multiplicador del espaciado entre líneas
  color: [255, 255, 255, 255]  # Color RGBA del texto
  start_size: 160         # Tamaño inicial de fuente en píxeles
  
  # Sombra exterior del texto
  outer_shadow:
    offset: [4, 4]        # Desplazamiento [x, y] en píxeles
    blur: 8               # Radio de desenfoque
    color: [0, 0, 0, 180] # Color RGBA de la sombra
  
  # Sombra interior del texto
  inner_shadow:
    offset: [3, 3]        # Desplazamiento [x, y] en píxeles
    blur: 3               # Radio de desenfoque
    color: [0, 0, 0, 120] # Color RGBA de la sombra

# Configuración de iconos
icons:
  max_width: 200          # Ancho máximo por icono en píxeles
  gap: 30                 # Separación entre iconos en píxeles
  
  # Sombra exterior de los iconos
  outer_shadow:
    offset: [4, 4]        # Desplazamiento [x, y] en píxeles
    blur: 8               # Radio de desenfoque
    color: [0, 0, 0, 180] # Color RGBA de la sombra

# Configuración de posicionamiento
layout:
  text_offset_y: -80      # Desplazamiento vertical del texto desde el centro
  icons_offset_y: 40      # Distancia entre texto e iconos

# Configuración de calidad de salida
output:
  png_quality: 95         # Calidad JPEG/PNG (1-100)
  create_psd: true        # Crear archivo PSD con capas separadas